environment: prod

deployment:
  replicas: 1
  image: skyere/greencity:latest
  requests:
    cpu: 10m
    memory: 200Mi
  limits:
    cpu: 2
    memory: 1024Mi

externalSecret:
  secretName: greencity-secret
  tenantId: 6c51c659-9d52-41af-81f7-dde16380e813
  vaultUrl: https://greencity-app.vault.azure.net

service:
  type: ClusterIP

# You need Nginx ingress controller and cert manager already installed
# https://kubernetes.github.io/ingress-nginx/deploy/
# https://cert-manager.io/docs/installation/helm/#3-install-customresourcedefinitions
ingress:
  enable_cors: true

  # Example: "https://origin-site.com:4443, http://origin-site.com, https://example.org:1199"
  # "https://*.origin-site.com:4443, http://*.origin-site.com"
  # If not set will be used "*" instead. Example: cors_allow_origin: ""
  cors_allow_origin: http://localhost:4200, http://localhost:4200/*, https://www.greencity.social/

  # Only when cors_allow_origin is not "*"
  cors_allow_credentials: "true"

  hostname: greencity.greencity.cx.ua
  
