{
  "os": "linux",
  "jdk": [
    "oraclejdk11"
  ],
  "dist": "trusty",
  "group": "stable",
  "script": [
    "git fetch --unshallow",
    "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ita-social-projects-green-city -Dsonar.organization=ita-social-projects -Dsonar.host.url=https://sonarcloud.io -Dtest='greencity.service.impl.*Test' -Dsonar.sources='src/main/java/greencity/service' -Dsonar.tests='src/test/java/greencity/service/impl' -Dsonar.binaries=target/classes -Dsonar.dynamicAnalysis=reuseReports"
  ],
  ".result": "configured",
  "language": "java"
}
